[2024-07-23T12:35:07.851+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-23T12:35:07.860+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: welcome_ais_dag.print_weather scheduled__2024-07-22T11:00:00+00:00 [queued]>
[2024-07-23T12:35:07.862+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: welcome_ais_dag.print_weather scheduled__2024-07-22T11:00:00+00:00 [queued]>
[2024-07-23T12:35:07.862+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-23T12:35:07.868+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): print_weather> on 2024-07-22 11:00:00+00:00
[2024-07-23T12:35:07.869+0000] {standard_task_runner.py:64} INFO - Started process 207 to run task
[2024-07-23T12:35:07.871+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'welcome_ais_dag', 'print_weather', 'scheduled__2024-07-22T11:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/welcome_dag.py', '--cfg-path', '/tmp/tmpv0od328s']
[2024-07-23T12:35:07.871+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask print_weather
[2024-07-23T12:35:07.886+0000] {task_command.py:426} INFO - Running <TaskInstance: welcome_ais_dag.print_weather scheduled__2024-07-22T11:00:00+00:00 [running]> on host 6995b00fe17f
[2024-07-23T12:35:07.909+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='welcome_ais_dag' AIRFLOW_CTX_TASK_ID='print_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-07-22T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-22T11:00:00+00:00'
[2024-07-23T12:35:07.909+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-23T12:35:08.159+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-23T12:35:08.161+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/welcome_dag.py", line 23, in print_weather
    timezone = response.json()['timezone']
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'timezone'
[2024-07-23T12:35:08.171+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=welcome_ais_dag, task_id=print_weather, run_id=scheduled__2024-07-22T11:00:00+00:00, execution_date=20240722T110000, start_date=20240723T123507, end_date=20240723T123508
[2024-07-23T12:35:08.187+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 17 for task print_weather ('timezone'; 207)
[2024-07-23T12:35:08.231+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-23T12:35:08.244+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-23T12:35:08.245+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
